// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password, appId
func (_m *MockAuth) Login(ctx context.Context, email string, password string, appId string) (string, error) {
	ret := _m.Called(ctx, email, password, appId)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, email, password, appId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, email, password, appId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, appId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuth_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuth_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - appId string
func (_e *MockAuth_Expecter) Login(ctx interface{}, email interface{}, password interface{}, appId interface{}) *MockAuth_Login_Call {
	return &MockAuth_Login_Call{Call: _e.mock.On("Login", ctx, email, password, appId)}
}

func (_c *MockAuth_Login_Call) Run(run func(ctx context.Context, email string, password string, appId string)) *MockAuth_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuth_Login_Call) Return(_a0 string, _a1 error) *MockAuth_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuth_Login_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockAuth_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password
func (_m *MockAuth) Register(ctx context.Context, email string, password string) (string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuth_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuth_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuth_Expecter) Register(ctx interface{}, email interface{}, password interface{}) *MockAuth_Register_Call {
	return &MockAuth_Register_Call{Call: _e.mock.On("Register", ctx, email, password)}
}

func (_c *MockAuth_Register_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuth_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuth_Register_Call) Return(_a0 string, _a1 error) *MockAuth_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuth_Register_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockAuth_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
